[args]
data_in = "fireducks_app/dataset"

[cluster]
verbose = true
cython = false
rapids = false
pool = false
cluster_enabled = false

[cluster.workers]
"127.0.0.1" = 1

[cluster.scheduler]
"127.0.0.1" = 1
