[args]
data_in = "fireducks_app/dataset"

[cluster]
verbose = true
cython = false
rapids = false
pool = false
cluster_enabled = false

[cluster.service_health]
allow_idle = false
max_unhealthy = 0
max_restart_rate = 0.25

[cluster.workers]
"127.0.0.1" = 1

[cluster.scheduler]
"127.0.0.1" = 1
