[project]
name = "view-maps-network"
version = "0.8.17"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.5.0",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
    "agi-env",
    "networkx",
    "plotly",
    "matplotlib",
]

[optional-dependencies]
dev = [
    "agi-env"
]

[tool.uv.sources.agi-env]
path = "../../core/agi-env"
editable = true
