[project]
name = "view-maps-network"
version = "2025.12.12"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.5.0",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
    "agi-env",
    "agi-node",
    "networkx",
    "plotly",
    "matplotlib",
    "sqlalchemy>=2.0.43",
    "scipy==1.15.2",
]
